import { defineConfig, type OxlintConfig, type OxlintOverride } from "oxlint";
import { defineRules } from "./defineRules";
import { pluginSpecifier } from "./plugin";

export const basePreset = {
	plugins: ["typescript", "eslint"],
	jsPlugins: [
		{
			name: "duplojs-plugin",
			specifier: pluginSpecifier,
		},
		{
			name: "@stylistic",
			specifier: "@stylistic/eslint-plugin",
		},
	],
	rules: defineRules({
		"array-callback-return": [
			"error",
			{
				checkForEach: true,
				allowVoid: true,
			},
		],
		"constructor-super": "error",
		"for-direction": "error",
		"getter-return": "error",
		"no-async-promise-executor": "error",
		"no-await-in-loop": "off",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-const-assign": "error",
		"no-constant-binary-expression": "error",
		"no-constant-condition": "warn",
		"no-constructor-return": "error",
		"no-control-regex": "error",
		"no-debugger": "warn",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-duplicate-imports": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-ex-assign": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-import-assign": "error",
		"no-inner-declarations": [
			"error",
			"functions",
			{
				namespaces: "allow",
			},
		],
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-obj-calls": "error",
		"no-promise-executor-return": [
			"error",
			{
				allowVoid: true,
			},
		],
		"no-prototype-builtins": "error",
		"no-self-assign": "error",
		"no-self-compare": "error",
		"no-setter-return": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "warn",
		"no-this-before-super": "error",
		"no-undef": "off",
		"no-unexpected-multiline": "error",
		"no-unmodified-loop-condition": "error",
		"no-unreachable": "warn",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-private-class-members": "warn",
		"no-useless-assignment": "off",
		"no-useless-backreference": "error",
		"use-isnan": "error",
		"valid-typeof": "error",
		"accessor-pairs": "error",
		"arrow-body-style": [
			"error",
			"as-needed",
		],
		"block-scoped-var": "error",
		"capitalized-comments": "off",
		"class-methods-use-this": "off",
		complexity: "off",
		curly: "error",
		"default-case": "off",
		"default-case-last": "off",
		eqeqeq: [
			"error",
			"always",
		],
		"func-name-matching": "error",
		"func-names": "off",
		"func-style": [
			"error",
			"declaration",
		],
		"grouped-accessor-pairs": "error",
		"guard-for-in": "off",
		"id-length": "error",
		"id-match": "off",
		"logical-assignment-operators": [
			"error",
			"always",
		],
		"max-classes-per-file": "error",
		"max-depth": "off",
		"max-lines": "off",
		"max-lines-per-function": "off",
		"max-nested-callbacks": "off",
		"max-statements": "off",
		"new-cap": [
			"error",
			{
				newIsCap: true,
				capIsNew: true,
				properties: true,
			},
		],
		"no-alert": "off",
		"no-bitwise": "error",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-console": "warn",
		"no-continue": "off",
		"no-delete-var": "error",
		"no-div-regex": "off",
		"no-else-return": "off",
		"no-empty": "warn",
		"no-empty-static-block": "warn",
		"no-eq-null": "error",
		"no-eval": "error",
		"no-extend-native": "off",
		"no-extra-bind": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-label": "error",
		"no-global-assign": "error",
		"no-implicit-coercion": [
			"error",
			{
				allow: ["!!"],
			},
		],
		"no-implicit-globals": "off",
		"no-implied-eval": "off",
		"no-inline-comments": "off",
		"no-iterator": "error",
		"no-label-var": "error",
		"no-labels": "off",
		"no-lone-blocks": "off",
		"no-lonely-if": "error",
		"no-multi-assign": "error",
		"no-multi-str": "error",
		"no-negated-condition": "off",
		"no-nested-ternary": "error",
		"no-new": "off",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-nonoctal-decimal-escape": "error",
		"no-object-constructor": "error",
		"no-param-reassign": "error",
		"no-plusplus": "off",
		"no-proto": "error",
		"no-redeclare": "off",
		"no-regex-spaces": "error",
		"no-restricted-exports": "off",
		"no-restricted-globals": "off",
		"no-restricted-imports": "off",
		"no-restricted-properties": "off",
		"no-return-assign": "error",
		"no-sequences": "error",
		"no-shadow": "off",
		"no-shadow-restricted-names": "error",
		"no-ternary": "off",
		"no-throw-literal": "off",
		"no-undefined": "off",
		"no-underscore-dangle": "off",
		"no-unneeded-ternary": "error",
		"no-unused-labels": "error",
		"no-useless-call": "error",
		"no-useless-catch": "error",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "error",
		"no-useless-return": "off",
		"no-var": "error",
		"no-void": "off",
		"no-warning-comments": "off",
		"no-with": "error",
		"object-shorthand": "off",
		"operator-assignment": "off",
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-destructuring": "off",
		"prefer-exponentiation-operator": "off",
		"prefer-named-capture-group": "off",
		"prefer-numeric-literals": "off",
		"prefer-object-has-own": "off",
		"prefer-object-spread": "error",
		"prefer-promise-reject-errors": "off",
		"prefer-regex-literals": "error",
		"prefer-template": "error",
		radix: "off",
		"require-await": "off",
		"require-unicode-regexp": "off",
		"require-yield": "error",
		"sort-imports": "off",
		"sort-keys": "off",
		"sort-vars": "off",
		"symbol-description": "error",
		"vars-on-top": "off",
		yoda: "error",
		"default-param-last": "error",
		"init-declarations": [
			"error",
			"always",
		],
		"max-params": [
			"error",
			{
				max: 4,
			},
		],
		"no-array-constructor": "error",
		"no-dupe-class-members": "error",
		"no-empty-function": "warn",
		"no-loop-func": "error",
		"no-loss-of-precision": "error",
		"no-magic-numbers": [
			"error",
			{
				ignoreEnums: true,
				ignoreNumericLiteralTypes: true,
				ignoreReadonlyClassProperties: true,
				ignoreTypeIndexes: true,
			},
		],
		"no-unused-expressions": "error",
		"no-unused-vars": [
			"warn",
			{
				ignoreRestSiblings: true,
				destructuredArrayIgnorePattern: "^_",
				argsIgnorePattern: "^_",
				varsIgnorePattern: "^_",
			},
		],
		"no-use-before-define": "error",

		"no-useless-constructor": "error",
		"typescript/adjacent-overload-signatures": "error",
		"typescript/array-type": "error",
		"typescript/await-thenable": "error",
		"typescript/ban-ts-comment": [
			"error",
			{
				"ts-expect-error": "allow-with-description",
			},
		],
		"typescript/ban-tslint-comment": "error",
		"typescript/class-literal-property-style": "error",
		"typescript/consistent-generic-constructors": "error",
		"typescript/consistent-indexed-object-style": "off",
		"typescript/consistent-return": "off",
		"typescript/consistent-type-assertions": "off",
		"typescript/consistent-type-definitions": "error",
		"typescript/consistent-type-exports": "off",
		"typescript/consistent-type-imports": [
			"error",
			{
				disallowTypeAnnotations: true,
				fixStyle: "inline-type-imports",
				prefer: "type-imports",
			},
		],
		"typescript/dot-notation": "error",
		"typescript/explicit-function-return-type": "off",
		"typescript/explicit-member-accessibility": "error",
		"typescript/explicit-module-boundary-types": "off",
		"typescript/method-signature-style": [
			"error",
			"method",
		],
		"typescript/no-array-delete": "error",
		"typescript/no-base-to-string": "error",
		"typescript/no-confusing-non-null-assertion": "error",
		"typescript/no-confusing-void-expression": [
			"error",
			{
				ignoreVoidOperator: true,
			},
		],
		"typescript/no-duplicate-enum-values": "error",
		"typescript/no-duplicate-type-constituents": "error",
		"typescript/no-dynamic-delete": "error",
		"typescript/no-empty-object-type": "off",
		"typescript/no-explicit-any": "error",
		"typescript/no-extra-non-null-assertion": "error",
		"typescript/no-extraneous-class": "off",
		"typescript/no-floating-promises": "error",
		"typescript/no-for-in-array": "error",
		"typescript/no-implied-eval": "error",
		"typescript/no-import-type-side-effects": "off",
		"typescript/no-inferrable-types": "error",
		"typescript/no-invalid-void-type": "error",
		"typescript/no-meaningless-void-operator": "off",
		"typescript/no-misused-new": "error",
		"typescript/no-misused-promises": "off",
		"typescript/no-mixed-enums": "error",
		"typescript/no-namespace": "off",
		"typescript/no-non-null-asserted-nullish-coalescing": "error",
		"typescript/no-non-null-asserted-optional-chain": "error",
		"typescript/no-non-null-assertion": "off",
		"typescript/no-redundant-type-constituents": "error",
		"typescript/no-require-imports": "error",
		"typescript/no-restricted-types": "off",
		"typescript/no-this-alias": "error",
		"typescript/no-unnecessary-boolean-literal-compare": "off",
		"typescript/no-unnecessary-condition": "off",
		"typescript/no-unnecessary-parameter-property-assignment": "error",
		"typescript/no-unnecessary-qualifier": "error",
		"typescript/no-unnecessary-template-expression": "error",
		"typescript/no-unnecessary-type-arguments": "off",
		"typescript/no-unnecessary-type-assertion": "off",
		"typescript/no-unnecessary-type-constraint": "off",
		"typescript/no-unnecessary-type-parameters": "off",
		"typescript/no-unsafe-argument": "error",
		"typescript/no-unsafe-assignment": "off",
		"typescript/no-unsafe-call": "error",
		"typescript/no-unsafe-declaration-merging": "error",
		"typescript/no-unsafe-enum-comparison": "error",
		"typescript/no-unsafe-function-type": "error",
		"typescript/no-unsafe-member-access": "error",
		"typescript/no-unsafe-return": "off",
		"typescript/no-unsafe-unary-minus": "error",
		"typescript/no-useless-empty-export": "error",
		"typescript/no-wrapper-object-types": "error",
		"typescript/non-nullable-type-assertion-style": "error",
		"typescript/only-throw-error": "error",
		"typescript/parameter-properties": "off",
		"typescript/prefer-as-const": "error",
		"typescript/prefer-enum-initializers": "error",
		"typescript/prefer-find": "error",
		"typescript/prefer-for-of": "error",
		"typescript/prefer-function-type": "error",
		"typescript/prefer-includes": "error",
		"typescript/prefer-literal-enum-member": "error",
		"typescript/prefer-namespace-keyword": "off",
		"typescript/prefer-nullish-coalescing": "off",
		"typescript/prefer-optional-chain": "error",
		"typescript/prefer-promise-reject-errors": "error",
		"typescript/prefer-readonly": "off",
		"typescript/prefer-readonly-parameter-types": "off",
		"typescript/prefer-reduce-type-parameter": "off",
		"typescript/prefer-regexp-exec": "off",
		"typescript/prefer-return-this-type": "error",
		"typescript/prefer-string-starts-ends-with": "error",
		"typescript/promise-function-async": "off",
		"typescript/require-array-sort-compare": "error",
		"typescript/require-await": "error",
		"typescript/restrict-plus-operands": "error",
		"typescript/restrict-template-expressions": "error",
		"typescript/return-await": "error",
		"typescript/strict-boolean-expressions": "off",
		"typescript/switch-exhaustiveness-check": "off",
		"typescript/triple-slash-reference": "error",
		"typescript/unbound-method": "off",
		"typescript/unified-signatures": "off",
		"typescript/use-unknown-in-catch-callback-variable": "error",

		// @stylistic/eslint-plugin
		"@stylistic/array-bracket-newline": [
			"error",
			{
				multiline: true,
			},
		],
		"@stylistic/array-bracket-spacing": [
			"error",
			"never",
		],
		"@stylistic/array-element-newline": [
			"error",
			{
				consistent: true,
				multiline: true,
			},
		],
		"@stylistic/arrow-parens": [
			"error",
			"always",
		],
		"@stylistic/arrow-spacing": "error",
		"@stylistic/block-spacing": "error",
		"@stylistic/brace-style": "error",
		"@stylistic/comma-dangle": [
			"error",
			"always-multiline",
		],
		"@stylistic/comma-spacing": [
			"error",
			{
				before: false,
				after: true,
			},
		],
		"@stylistic/comma-style": [
			"error",
			"last",
		],
		"@stylistic/computed-property-spacing": [
			"error",
			"never",
		],
		"@stylistic/dot-location": [
			"error",
			"property",
		],
		"@stylistic/eol-last": [
			"error",
			"always",
		],
		"@stylistic/function-call-spacing": [
			"error",
			"never",
		],
		"@stylistic/function-call-argument-newline": [
			"error",
			"consistent",
		],
		"@stylistic/function-paren-newline": [
			"error",
			"multiline-arguments",
		],
		"@stylistic/generator-star-spacing": [
			"error",
			{
				before: true,
				after: false,
			},
		],
		"@stylistic/implicit-arrow-linebreak": [
			"error",
			"beside",
		],
		"@stylistic/jsx-quotes": [
			"error",
			"prefer-double",
		],
		"@stylistic/key-spacing": [
			"error",
			{
				beforeColon: false,
				afterColon: true,
			},
		],
		"@stylistic/keyword-spacing": [
			"error",
			{
				before: true,
				after: true,
			},
		],
		"@stylistic/line-comment-position": [
			"error",
			{
				position: "above",
			},
		],
		"@stylistic/linebreak-style": [
			"error",
			"unix",
		],
		"@stylistic/lines-around-comment": [
			"error",
			{
				beforeBlockComment: true,
			},
		],
		"@stylistic/lines-between-class-members": [
			"error",
			"always",
			{
				exceptAfterOverload: true,
			},
		],
		"@stylistic/max-len": [
			"error",
			{
				code: 120,
				ignoreStrings: true,
				ignoreTemplateLiterals: true,
				ignoreRegExpLiterals: true,
			},
		],
		"@stylistic/max-statements-per-line": [
			"error",
			{
				max: 1,
			},
		],
		"@stylistic/multiline-ternary": [
			"error",
			"always-multiline",
		],
		"@stylistic/new-parens": "error",
		"@stylistic/newline-per-chained-call": [
			"error",
			{
				ignoreChainWithDepth: 3,
			},
		],
		"@stylistic/no-extra-semi": "error",
		"@stylistic/no-floating-decimal": "error",
		"@stylistic/no-mixed-operators": "error",
		"@stylistic/no-mixed-spaces-and-tabs": "error",
		"@stylistic/no-multi-spaces": "error",
		"@stylistic/no-multiple-empty-lines": [
			"error",
			{
				max: 1,
				maxEOF: 1,
			},
		],
		"@stylistic/no-tabs": [
			"error",
			{
				allowIndentationTabs: true,
			},
		],
		"@stylistic/no-trailing-spaces": "error",
		"@stylistic/no-whitespace-before-property": "error",
		"@stylistic/nonblock-statement-body-position": [
			"error",
			"beside",
		],
		"@stylistic/object-curly-newline": [
			"error",
			{
				consistent: true,
				multiline: true,
			},
		],
		"@stylistic/object-curly-spacing": [
			"error",
			"always",
		],
		"@stylistic/object-property-newline": "error",
		"@stylistic/one-var-declaration-per-line": [
			"error",
			"always",
		],
		"@stylistic/operator-linebreak": [
			"error",
			"before",
			{
				overrides: {
					"=": "after",
				},
			},
		],
		"@stylistic/padded-blocks": [
			"error",
			"never",
		],
		"@stylistic/quote-props": [
			"error",
			"as-needed",
		],
		"@stylistic/quotes": [
			"error",
			"double",
		],
		"@stylistic/rest-spread-spacing": [
			"error",
			"never",
		],
		"@stylistic/semi": [
			"error",
			"always",
		],
		"@stylistic/semi-spacing": "error",
		"@stylistic/semi-style": [
			"error",
			"last",
		],
		"@stylistic/space-before-blocks": "error",
		"@stylistic/space-before-function-paren": [
			"error",
			{
				anonymous: "never",
				named: "never",
				asyncArrow: "never",
				catch: "always",
			},
		],
		"@stylistic/space-in-parens": [
			"error",
			"never",
		],
		"@stylistic/space-infix-ops": "error",
		"@stylistic/space-unary-ops": "error",
		"@stylistic/switch-colon-spacing": "error",
		"@stylistic/template-curly-spacing": "error",
		"@stylistic/template-tag-spacing": "error",
		"@stylistic/wrap-iife": [
			"error",
			"inside",
		],
		"@stylistic/yield-star-spacing": [
			"error",
			"before",
		],
		"@stylistic/indent": [
			"error",
			"tab",
		],
		"@stylistic/member-delimiter-style": "error",
		"@stylistic/type-annotation-spacing": "error",

		// duplojs-plugin
		"duplojs-plugin/no-unreachable-loop": "error",
		"duplojs-plugin/camelcase": "error",
		"duplojs-plugin/dot-notation": "error",
		"duplojs-plugin/prefer-destructuring": [
			"error",
			{
				array: true,
			},
		],
	}),
} as const satisfies Omit<OxlintOverride, "files">;

/**
 * @internal
 */
export const basePresetConfig = {
	categories: {
		correctness: "off",
		nursery: "off",
		pedantic: "off",
		perf: "off",
		restriction: "off",
		style: "off",
		suspicious: "off",
	},
	options: {
		typeAware: true,
		reportUnusedDisableDirectives: "error",
		respectEslintDisableDirectives: true,
	},
} as const satisfies OxlintConfig;

export const baseConfig = defineConfig({
	...basePreset,
	...basePresetConfig,
});
